version: '3.9'

services:
  location-service:
    build: 
      context: ../../../
      dockerfile: ./server/services/location-service/Dockerfile
    restart: always
    volumes:
      - ../../../build/server/locationService:/app/locationService
    ports:
      - "87:8888"
    environment:
      - SERVER_MODE=development
      - DB_PASSWORD=123456
    networks:
      - petifies

  location-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://location-mongo-1:27017,location-mongo-2:27017,location-mongo-3:27017/?replicaSet=my-location-mongo-set
    networks:
      - petifies
