version: '3.9'

services:
  petifies-service:
    build: 
      context: ../../../
      dockerfile: ./server/services/petifies-service/Dockerfile
    restart: always
    volumes:
      - ../../../build/server/petifiesService:/app/petifiesService
    ports:
      - "98:8888"
    environment:
      - SERVER_MODE=development
      - DB_PASSWORD=123456
    networks:
      - petifies

  petifies-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://petifies-mongo-1:27017,petifies-mongo-2:27017,petifies-mongo-3:27017/?replicaSet=my-petifies-mongo-set
    networks:
      - petifies
