version: '3.9'

services:
  post-service:
    build: 
      context: ../../../
      dockerfile: ./server/services/post-service/Dockerfile
    restart: always
    volumes:
      - ../../../build/server/postService:/app/postService
    ports:
      - "82:8888"
    environment:
      - SERVER_MODE=development
      - DB_PASSWORD=123456
    networks:
      - petifies

  post-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://post-mongo-1:27017,post-mongo-2:27017,post-mongo-3:27017/?replicaSet=my-mongo-set
    networks:
      - petifies
