version: '3.9'

services:
  post-service:
    build: 
      context: ../../../
      dockerfile: ./server/services/post-service/Dockerfile
    restart: always
    volumes:
      - ../../../build/server/postService:/app/postService
    ports:
      - "82:8888"
    environment:
      - SERVER_MODE=development
    networks:
      - petifies

  post-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@post-mongo:27017/
