version: '3.9'

services:
  user-service:
    build:
      context: ../../../
      dockerfile: ./server/services/user-service/Dockerfile
    restart: always
    volumes:
      - ../../../build/server/userService:/app/userService
    environment:
      - SERVER_MODE=development
    networks:
      - petifies
      