GrpcPort: 8888
Domain:
TLSKeyPath: "/app/cert/tls.key"
TLSCertPath: "/app/cert/tls.crt" 
UserServiceHost: "user-service:8888"
PostServiceHost: "post-service:8888"
MediaServiceHost: "media-service:8888"