GrpcPort: 8888
Domain:
TLSKeyPath: "/app/cert/tls.key"
TLSCertPath: "/app/cert/tls.crt" 
UserServiceHost: "user-service:8888"
PostServiceHost: "post-service:8888"
MediaServiceHost: "media-service:8888"
RelationshipServiceHost: "relationship-service:8888"
NewfeedServiceHost: "newfeed-service:8888"
PetifiesServiceHost: "petifies-service:8888"
LocationServiceHost: "location-service:8888"
RedisURL: "central-cache:6379"
RedisUser: ""
RedisPassword: ""
RedisDatabase: 0