GrpcPort: 8888
Domain:
CassandraUrl: "newfeed-cassandra:9042"
CassandraUser: "cassandra"
CassandraPassword: "cassandra"
Keyspace: "newfeed"
UserEventTopic: "user-event"
UserEventConsumerGroup: "newfeed-user-event-consumer-group"
PostEventTopic: "post-event"
PostEventConsumerGroup: "newfeed-post-event-consumer-group"
Brokers: 
  - kafka-broker-1:9092
  - kafka-broker-2:9092
  - kafka-broker-3:9092
RelationshipServiceHost: "relationship-service:8888"
