GrpcPort: 8888
Domain:
MongoUrl: "mongodb://location-mongo-1:27017,location-mongo-2:27017,location-mongo-3:27017/?replicaSet=my-location-mongo-set"
DatabaseName: "locationServiceDatabase"
UserEventTopic: user-event
UserEventConsumerGroup: location-user-consumer-group
PetifiesEventTopic:  "petifies-event"
PetifiesEventConsumerGroup: location-petifies-consumer-group
Brokers: 
  - kafka-broker-1:9092
  - kafka-broker-2:9092
  - kafka-broker-3:9092