name: Server CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq
        sudo apt install -y protobuf-compiler
        sudo apt install golang-goprotobuf-dev
        jq --version
        go mod download
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        export PATH="$PATH:$(go env GOPATH)/bin"
        make gen_proto

    # - name: Linting
    #   run: |
    #     golangci-lint run --out-format=github-actions -- $(go work edit -json | jq -c -r '[.Use[].DiskPath] | map_values(. + "/...")[]')

    - name: Bring up the server using docker compose
      id: build-image
      run: |
        make ci_up_build
