name: Server CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq
        jq --version
        go mod download
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        make gen_proto

    - name: Linting
      run: |
        golangci-lint run --out-format=github-actions -- $(go work edit -json | jq -c -r '[.Use[].DiskPath] | map_values(. + "/...")[]')

    - name: Bring up the server using docker compose
      id: build-image
      run: |
        make up_build
